# Site settings
title: Northwestern Course Data API
email: asg-technology@u.northwestern.edu
description: "Learn how to use Northwestern University course data in your programs and applications! Visit this page to read documentation and apply for keys."
baseurl: ""
url: "http://developer.asg.northwestern.edu"
twitter_username: northwesternasg
github_username:  northwesternapi

# Build settings
markdown: kramdown
permalink: pretty
